"""empty message

Revision ID: 293b87fc7d23
Revises: e2b8fc5e23b4
Create Date: 2021-11-01 14:04:57.890090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293b87fc7d23'
down_revision = 'e2b8fc5e23b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    # ### end Alembic commands ###
